#!/bin/bash

source /opt/miniconda3/bin/activate mlbox

appdir="${HOME}/storage/jupyter"
notedir="${HOME}/storage/notebooks"

mkdir -p "${appdir}"
mkdir -p "${notedir}"

exec jupyter lab --app-dir "${appdir}" --notebook-dir "${notedir}" "$@"
